// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIuANNp-DyTAtkLKsfCkm0dB4RkK_fYw',
    appId: '1:474575612648:web:6e3a08cc8f926fc118375d',
    messagingSenderId: '474575612648',
    projectId: 'hamiimobiles-b8a3e',
    authDomain: 'hamiimobiles-b8a3e.firebaseapp.com',
    storageBucket: 'hamiimobiles-b8a3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrs_OfoVU1_kwdPbAkh4Zeo2FaMNcFdfk',
    appId: '1:474575612648:android:0b96070ba73e962518375d',
    messagingSenderId: '474575612648',
    projectId: 'hamiimobiles-b8a3e',
    storageBucket: 'hamiimobiles-b8a3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7JLsoF5V_65xao8-yVX7E5xfNsOJe2Bo',
    appId: '1:474575612648:ios:6ece14c0f788956f18375d',
    messagingSenderId: '474575612648',
    projectId: 'hamiimobiles-b8a3e',
    storageBucket: 'hamiimobiles-b8a3e.firebasestorage.app',
    iosBundleId: 'com.example.hamii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7JLsoF5V_65xao8-yVX7E5xfNsOJe2Bo',
    appId: '1:474575612648:ios:6ece14c0f788956f18375d',
    messagingSenderId: '474575612648',
    projectId: 'hamiimobiles-b8a3e',
    storageBucket: 'hamiimobiles-b8a3e.firebasestorage.app',
    iosBundleId: 'com.example.hamii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQIuANNp-DyTAtkLKsfCkm0dB4RkK_fYw',
    appId: '1:474575612648:web:778f4c9899da281b18375d',
    messagingSenderId: '474575612648',
    projectId: 'hamiimobiles-b8a3e',
    authDomain: 'hamiimobiles-b8a3e.firebaseapp.com',
    storageBucket: 'hamiimobiles-b8a3e.firebasestorage.app',
  );

}